#!/bin/bash
set -e

# Define paths
CONFIG_FILE=/usr/local/share/mod_dp/config/mod_dp.conf
APACHE_CONF_DIR=/etc/apache2/mods-available
APACHE_CONF_ENABLED_DIR=/etc/apache2/mods-enabled

# Copy the configuration file to Apache's mods-available directory
cp "$CONFIG_FILE" "$APACHE_CONF_DIR"

# Create a symlink in the mods-enabled directory
ln -s "$APACHE_CONF_DIR/mod_dp.conf" "$APACHE_CONF_ENABLED_DIR/mod_dp.conf"

# Enable the module
a2enmod directpython

# Reload Apache to apply the changes
systemctl reload apache2